=== esorzai503/LengMarcas/TEMA 1/XML/videoteca.dtd
<!ELEMENT videoteca (pelicula+)>
<!-- donde pone "pelicula+, significa quer hay mas d una pelicula en "vdeioteca, en caso de q queramos
poner mas directores o titulo, etc. dentro de una etiqueta, hay que poner (nombre)+ -->
<!ELEMENT pelicula (titulo,director,anio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!-- en PCDATA significa q los elementos q tienen ese parentesis son ya datos, que se han vuelto datos, y se
 identifica con el (nombre) (#PCDATA)-->

=== esorzai503/LengMarcas/TEMA 1/XML/videoteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoteca SYSTEM "videoteca.dtd">

<videoteca>
    <pelicula>
      <titulo>Mar Adentro</titulo>
      <director>Am√©nabar</director>
      <anio>2004</anio>
    </pelicula>
    <pelicula>
        <titulo>Jumanji</titulo>
        <director>Jake Kasdan</director>
        <anio>1995</anio>
    </pelicula>
    <pelicula>
        <titulo>Matrix</titulo>
        <director></director>
        <anio>1999</anio>
    </pelicula>
</videoteca>
